spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/satyabratasahoo
    username: satyabratasahoo
    password: satya123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
